---
- name: pip install gunicorn
  pip: name=gunicorn
  become: True

- name: pip install newsbeuter-spread requirements.txt
  pip: requirements={{ newsbeuter_spread_path }}requirements.txt
  become: True
  notify:
  - Restart newsbeuter
