---
- name: Generate supervisord file (debian)
  when: ansible_os_family == 'Debian'
  template: src=newsbeuter.conf.j2
          dest=/etc/supervisor/conf.d/newsbeuter.conf
          owner=root
          group=root
          mode=640
  notify:
  - Read newsbeuter

- name: Generate supervisord file (rhel)
  when: ansible_os_family != 'Debian'
  template: src=newsbeuter.conf.j2
          dest=/etc/supervisord.d/newsbeuter.conf
          owner=root
          group=root
          mode=640
  notify:
  - Read newsbeuter
